# Make colorschemes appear correctly
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm*:RGB'

# Change prefix to Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Make new windows start after current
bind c new-window -a -c "#{pane_current_path}"
bind C new-window -c "#{pane_current_path}"

# Vim-style splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Vim-style copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection
set -g allow-passthrough on
set -s set-clipboard on
setw -g mode-style 'fg=#a7d8b0'

# Start from window index 1
set -g base-index 1

# Automatically renumber-windows
set -g renumber-windows on

# Rename window to dir instead of process
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

# Styling of status line (sessions, windows, panes)
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=default'

set -g status-left-style 'fg=#e1ffe5'
set -g status-left ' #S '
set -g status-left-length 20
set -g status-right ''

set -g pane-border-lines single
set -g pane-border-style 'fg=#554A62'
set -g pane-active-border-style 'fg=#787487'

setw -g window-status-separator ''
setw -g window-status-format '  #I:#W #F  '
setw -g window-status-style 'bg=default,fg=#787487'
setw -g window-status-current-format '  #I:#W #F  '
setw -g window-status-current-style 'bg=default,fg=#9f9e99'


# F12 nested session toggle

# F12 nested session toggle
bind -T root 'C-`' \
  set prefix None \;\
  set key-table off \;\
  setw -g window-status-style 'fg=#554a62' \;\
  setw -g window-status-current-style 'fg=#554a62' \;\
  set -g status-left-style 'fg=#554a62' \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

bind -T off 'C-`' \
  set -u prefix \;\
  set -u key-table \;\
  set -u window-status-style \;\
  setw -g window-status-style 'bg=default,fg=#787487' \;\
  setw -g window-status-current-style 'bg=default,fg=#9f9e99' \;\
  set -g status-left-style 'fg=#e1ffe5' \;\
  refresh-client -S

# Window swapping
bind -r Left swap-window -t -1 \; select-window -t -1
bind -r Right swap-window -t +1 \; select-window -t +1

# Agent notifications
setw -g monitor-bell on
set -g bell-action other # only monitor bells in windows not currently open
setw -g window-status-bell-style 'fg=#787487 underscore'

# Correctly pass modified keys to processes running in tmux
set -g extended-keys on
set -g extended-keys-format csi-u
